Увеличение занимаемого картой пространства на мобильных устройствах
dtpstat/website pull request #105
Opened 2022-04-09 11:28 UTC by PiRomant

![map (1)](https://user-images.githubusercontent.com/29551044/162569754-30b3e4ae-cb8b-4c3b-950d-e46d4b434874.jpg)![map (2)](https://user-images.githubusercontent.com/29551044/162569752-4444780c-6e81-4002-9074-882ac7f893fa.jpg)

2022-07-07 13:19 UTC, stereodenis requested changes

2022-07-07 13:19 UTC, stereodenis commented on src/styles/inherited-scss/components/filter-panel/_filter-panel.scss
> +    padding-bottom: 15px;
```suggestion
    padding: 6px 16px 15px;
```

2022-07-07 13:27 UTC, sergous submitted a review, later dismissed

2022-07-09 14:08 UTC, stereodenis approved these changes

2022-07-09 17:54 UTC, sergous approved these changes

2023-11-13 14:58 UTC, merged

2023-11-13 15:00 UTC, alexander-mart commented
@PiRomant кажется ничего не изменилось :thinking: 
Что я делаю не так?
https://65523809027d4b00082c7e2f--dtp-stat.netlify.app/