Restore map icons
dtpstat/website pull request #81
Opened 2022-02-13 12:10 UTC by kachkaev

Closes #76, closes #77

Out of scope: clusters (#79) – to be explored after release

2022-02-13 13:58 UTC, PiRomant requested changes
Надо вернуть и `groupByCoordinates: true`, а то не будет видно точек с одними и теми же координатами
https://github.com/dtpstat/dtp-map/pull/35/commits/24a91402f46f74e0aa496af5c938dca516324631#diff-d7e30a69eb5704209043473a282756fdd987f07ebf0d2e3983e41b5781c3d9b6L80

2022-02-13 16:16 UTC, PiRomant commented
Упала производительность по сравнению с предрелизом

https://user-images.githubusercontent.com/29551044/153762157-7562dcaf-53c1-4d05-9ecd-76b141213e3a.mp4

2022-02-13 18:43 UTC, alexander-mart commented
Не могу воспроизвести кластеры по ссылке. При каких условиях они должны появиться?

2022-02-14 15:56 UTC, alexander-mart commented
@PiRomant Этот PR больше не актулен?

2022-02-14 16:03 UTC, kachkaev commented
Replaced by https://github.com/dtpstat/website/pull/82

2022-02-14 16:03 UTC, closed without merging